### ISSUE TITLE
Clear selection bug when no available options

### ISSUE THREAD

**Issue by tmonfre** [dali-lab/pine-beetle-frontend#494]
# Description

Replication steps:

1) Click on trapping data page. Click on RD toggle. Select Alabama. Select Bankhead RD. So far so good.

2) Decide to switch to county view, click on county toggle. Go to select state, menu not available, only "clear selection" appears. (So now it seems like county selections are not available, since you can't select a state.)

3) Click back on RD toggle. Figure adjusts back to showing the data for all Alabama RDs. Click on state selector, which now shows Alabama, plus clear selection. Click clear selection. Full state menu reappears.

4) County toggle now works.

5) The same sequence of events is roughly the same on the prediction page, and also happens in reverse order (so if you start with counties and want to switch to RDs). I replicated the bug in both Firefox and Chrome, but was not able to access the site at all on Edge.

## Type of Issue

- [ ] New feature
- [x] Bug fix
- [ ] Documentation update

**Comment by jeffzyliu** [comment]
This is a 2.0 bug which is no longer relevant
